### ISSUE TITLE
Create a python application which reads from a given config file with the following features

### ISSUE THREAD

**Issue by iamvishnuks** [xmigrate/xforecast#2]
**Objective**
Create a python application which could read from a configuration file as defined below,

```
prometheus_url: https://jfkjdsf.fdfs.com

metrics:
- name: cpu_usage  #metric name in prometheus
  training_interval: 7hr #amount of data should be used for training
  forecast_duration: 5m #How data points should be predicted, here it will predict for 5 mins
  forecast_every: 1m #At what interval the app do the predictions 
  forecast_basedon: 10m #Forecast based on past how many data points
  write_back_metric: forecast_cpu_usage #Where should it write back the metrics
  retrain: True
  start_time: 10:20:00
  end_time: 12:00:00
 
- name: mem_usage  #metric name in prometheus
  training_interval: 7hr #amount of data should be used for training
  forecast_duration: 5m #How data points should be predicted, here it will predict for 5 mins
  forecast_every: 1m #At what interval the app do the predictions 
  forecast_basedon: 10m #Forecast based on past how many data points
  write_back_metric: forecast_cpu_usage #Where should it write back the metrics
  retrain: True
  start_time: 10:20:00
  end_time: 12:00:00
```

This application should have the following features,
- [x] retrain the model
- [x] predict the values

Training and predicting should be based on the values passed in the configuration file.
Refer this issue for more information:  https://github.com/xmigrate/kube-forecast/issues/1

**Outcome**
- forecaster app should be able to retrain the model from the values given in the config yaml
- forecaster app should be able to predict the data points as defined in the config yaml
